### ISSUE TITLE
allow newlines in any variable?

### ISSUE THREAD

**Issue by inputsprocket** [adamlc/address-format#15]
since STREET_ADDRESS can only accept a single line, which is an issue, a simple fix would be on line 113 of Format.php to add:

```
   $formatted_address = str_replace("\n", "%n", $formatted_address);
   $formatted_address = str_replace('%n', "\n" . '<br>', $formatted_address);
```

instead of

```
   $formatted_address = str_replace('%n', "\n" . '<br>', $formatted_address);
```

that way, any variable could have multiple lines, at the user's choice..

**Comment by adamlc** [comment]
Hi @inputsprocket thanks for your input! Feel free to submit a PR and write a test!

I'm not sure if this would cause any issues yet. In your street address field are you passing a string with a new line in? We might need to think of a way of handling this regardless
