### ISSUE TITLE
Validate data passed to setLocale

### ISSUE THREAD

**Issue by robehickman** [adamlc/address-format#16]
The method setLocale($locale) passes $locale to file_get_contents after a concatenation, but with no input validation. If this was user controlled data, which is possible, it would allow directory traversal.

As far as I can see $locale should always be a string of two capital A to Z letters, it would be sensible to validate, or give an indication that this should be done by the user in the readme.

**Comment by adamlc** [comment]
Makes sense, sadly I don't really write PHP any more, but feel free to submit a PR and I'll gladly merge it :)
