### ISSUE TITLE
City is not displayed for AD

### ISSUE THREAD

**Issue by luigifab** [adamlc/address-format#17]
Example:
```
Name
Company
Street
AD100
Andorre
```

I changed in AD.json, `"fmt": "%N%n%O%n%A%n%Z %S"` to `"fmt": "%N%n%O%n%A%n%Z %C %S"`.
Result:
```
Name
Company
Street
AD100 Canillo
Andorre
```

**Comment by crishoj** [comment]
City appears with the updated format for `AD` in #22:

```
%N%n%O%n%A%n%Z %C
```
