### ISSUE TITLE
Postcode is not displayed for IE

### ISSUE THREAD

**Issue by luigifab** [adamlc/address-format#18]
Example:
```
Name
Company
Street
Dublin
Ireland
```

I changed in IE.json, `"fmt": "%N%n%O%n%A%n%C%n%S"` to `"fmt": "fmt": "%N%n%O%n%A%n%C%n%Z%n%S"`.
Result:
```
Name
Company
Street
Dublin
D24 YN15
Ireland
```

**Comment by crishoj** [comment]
Postcode is included in the new format for `IE` in #22
